<a href="https://colab.research.google.com/github/sairohitt18/Machine-Learning-IPL-Cricket-Score-Prediction/blob/main/SML_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from scipy import stats
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor


In [ ]:
url="https://raw.githubusercontent.com/anujvyas/IPL-First-Innings-Score-Prediction-Deployment/master/ipl.csv"
df=pd.read_csv(url)

In [ ]:
df.tail()

mid        date                                      venue  \
76009  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal   
76010  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal   
76011  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal   
76012  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal   
76013  617  2017-05-21  Rajiv Gandhi International Stadium, Uppal   

             bat_team               bowl_team     batsman        bowler  runs  \
76009  Mumbai Indians  Rising Pune Supergiant   KH Pandya  DT Christian   121   
76010  Mumbai Indians  Rising Pune Supergiant   KH Pandya  DT Christian   127   
76011  Mumbai Indians  Rising Pune Supergiant   KH Pandya  DT Christian   128   
76012  Mumbai Indians  Rising Pune Supergiant  MG Johnson  DT Christian   129   
76013  Mumbai Indians  Rising Pune Supergiant   KH Pandya  DT Christian   129   

       wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
76009        7   19.2           40               0       40           12   
76010        7   19.3           46               0       46           12   
76011        7   19.4           47               0       47           12   
76012        7   19.5           48               0       47           13   
76013        8   19.6           47               1       47           13   

       total  
76009    129  
76010    129  
76011    129  
76012    129  
76013    129

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76014 entries, 0 to 76013
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   mid             76014 non-null  int64  
 1   date            76014 non-null  object 
 2   venue           76014 non-null  object 
 3   bat_team        76014 non-null  object 
 4   bowl_team       76014 non-null  object 
 5   batsman         76014 non-null  object 
 6   bowler          76014 non-null  object 
 7   runs            76014 non-null  int64  
 8   wickets         76014 non-null  int64  
 9   overs           76014 non-null  float64
 10  runs_last_5     76014 non-null  int64  
 11  wickets_last_5  76014 non-null  int64  
 12  striker         76014 non-null  int64  
 13  non-striker     76014 non-null  int64  
 14  total           76014 non-null  int64  
dtypes: float64(1), int64(8), object(6)
memory usage: 8.7+ MB


In [ ]:
##DATA CLEANING##
#REMOVING UNWANTED COLUMNS##
columns_to_remove = ['mid', 'venue', 'batsman', 'bowler', 'striker', 'non-striker']
df.drop(labels=columns_to_remove, axis=1, inplace=True)

In [ ]:
df.head()

date               bat_team                    bowl_team  runs  \
0  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
1  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
2  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
3  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
4  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   

   wickets  overs  runs_last_5  wickets_last_5  total  
0        0    0.1            1               0    222  
1        0    0.2            1               0    222  
2        0    0.2            2               0    222  
3        0    0.3            2               0    222  
4        0    0.4            2               0    222

In [ ]:
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
                    'Mumbai Indians', 'Kings XI Punjab', 'Royal Challengers Bangalore',
                    'Delhi Daredevils', 'Sunrisers Hyderabad']

In [ ]:
df = df[(df['bat_team'].isin(consistent_teams)) & (df['bowl_team'].isin(consistent_teams))]

In [ ]:
df = df[df['overs']>=5.0]

In [ ]:
df.head()

date               bat_team                    bowl_team  runs  \
32  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
33  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
34  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
35  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
36  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   

    wickets  overs  runs_last_5  wickets_last_5  total  
32        0    5.1           59               0    222  
33        1    5.2           59               1    222  
34        1    5.3           59               1    222  
35        1    5.4           59               1    222  
36        1    5.5           58               1    222

In [ ]:
print(df['bat_team'].unique())
print(df['bowl_team'].unique())

['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Kings XI Punjab' 'Royal Challengers Bangalore'
 'Delhi Daredevils' 'Sunrisers Hyderabad']
['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Rajasthan Royals' 'Mumbai Indians' 'Chennai Super Kings'
 'Kolkata Knight Riders' 'Sunrisers Hyderabad']


In [ ]:
from datetime import datetime
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [ ]:
# --- Data Preprocessing ---
# Converting categorical features using OneHotEncoding method
encoded_df = pd.get_dummies(data=df, columns=['bat_team', 'bowl_team'])

In [ ]:
encoded_df.head()

date  runs  wickets  overs  runs_last_5  wickets_last_5  total  \
32 2008-04-18    61        0    5.1           59               0    222   
33 2008-04-18    61        1    5.2           59               1    222   
34 2008-04-18    61        1    5.3           59               1    222   
35 2008-04-18    61        1    5.4           59               1    222   
36 2008-04-18    61        1    5.5           58               1    222   

    bat_team_Chennai Super Kings  bat_team_Delhi Daredevils  \
32                             0                          0   
33                             0                          0   
34                             0                          0   
35                             0                          0   
36                             0                          0   

    bat_team_Kings XI Punjab  ...  bat_team_Royal Challengers Bangalore  \
32                         0  ...                                     0   
33                         0  ...                                     0   
34                         0  ...                                     0   
35                         0  ...                                     0   
36                         0  ...                                     0   

    bat_team_Sunrisers Hyderabad  bowl_team_Chennai Super Kings  \
32                             0                              0   
33                             0                              0   
34                             0                              0   
35                             0                              0   
36                             0                              0   

    bowl_team_Delhi Daredevils  bowl_team_Kings XI Punjab  \
32                           0                          0   
33                           0                          0   
34                           0                          0   
35                           0                          0   
36                           0                          0   

    bowl_team_Kolkata Knight Riders  bowl_team_Mumbai Indians  \
32                                0                         0   
33                                0                         0   
34                                0                         0   
35                                0                         0   
36                                0                         0   

    bowl_team_Rajasthan Royals  bowl_team_Royal Challengers Bangalore  \
32                           0                                      1   
33                           0                                      1   
34                           0                                      1   
35                           0                                      1   
36                           0                                      1   

    bowl_team_Sunrisers Hyderabad  
32                              0  
33                              0  
34                              0  
35                              0  
36                              0  

[5 rows x 23 columns]

In [ ]:
encoded_df.columns

Index(['date', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'total', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')

In [ ]:
# Rearranging the columns
encoded_df = encoded_df[['date', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils', 'bat_team_Kings XI Punjab',
              'bat_team_Kolkata Knight Riders', 'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
              'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
              'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils', 'bowl_team_Kings XI Punjab',
              'bowl_team_Kolkata Knight Riders', 'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
              'bowl_team_Royal Challengers Bangalore', 'bowl_team_Sunrisers Hyderabad',
              'overs', 'runs', 'wickets', 'runs_last_5', 'wickets_last_5', 'total']]

In [ ]:
X_train = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year <= 2016]
X_test = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year >= 2017]

In [ ]:
y_train = encoded_df[encoded_df['date'].dt.year <= 2016]['total'].values
y_test = encoded_df[encoded_df['date'].dt.year >= 2017]['total'].values

In [ ]:
y_train

array([222, 222, 222, ..., 208, 208, 208], dtype=int64)

In [ ]:
X_train.drop(labels='date', axis=True, inplace=True)
X_test.drop(labels='date', axis=True, inplace=True)

In [ ]:
# --- Model Building ---
# Linear Regression Model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)


LinearRegression()

In [ ]:
prediction=regressor.predict(X_test)

In [ ]:
prediction

array([172.07093429, 175.2197967 , 174.61607874, ..., 100.37504751,
        99.80473879,  93.14382211])

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, prediction))
print('MSE:', metrics.mean_squared_error(y_test, prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, prediction)))

MAE: 12.118617546193295
MSE: 251.0079231041742
RMSE: 15.8432295667321


In [ ]:
np.mean(df['total'])

161.94751670489677

In [ ]:
np.median(df['total'])

163.0

In [ ]:
stats.mode(df['total'])

C:\Users\dell\AppData\Local\Temp\ipykernel_3320\1289752990.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(df['total'])


ModeResult(mode=array([183], dtype=int64), count=array([935]))

In [ ]:
RF= RandomForestRegressor()

In [ ]:
RF.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
rf_prediction=RF.predict(X_test)

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, rf_prediction))
print('MSE:', metrics.mean_squared_error(y_test, rf_prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test,rf_prediction)))


MAE: 13.81535781137509
MSE: 335.63945873066154
RMSE: 18.32046557079436


In [ ]:
DT= DecisionTreeRegressor()

In [ ]:
DT.fit(X_train, y_train)

DecisionTreeRegressor()

In [ ]:
DT_prediction=DT.predict(X_test)

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, DT_prediction))
print('MSE:', metrics.mean_squared_error(y_test, DT_prediction))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test,DT_prediction)))

MAE: 16.66918646508279
MSE: 514.2710583153348
RMSE: 22.677545244477738


In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
X, y = load_iris(return_X_y=True)

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
A = [[0], [1], [2], [3]]
B = [0, 0, 1, 1]

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(A,B)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
print(neigh.predict([[1.1]]))

[0]


D:\ANACONDA\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
